### ISSUE TITLE
Identify 10 high-complexity methods.

### ISSUE THREAD

**Issue by Carnoustie** [GroupFiveSW/Algorithms#2]
Identify 10 functions/methods with high code complexity. Document the purpose of them, and why
the complexity should be high (or not).

**Comment by Klako** [comment]
Warnings (cyclomatic_complexity > 15 or length > 1000 or nloc > 1000000 or parameter_count > 100)

     NLOC   CCN  token    PARAM  length  location
     113     91   1384      4     150 QuadTree::Node::knn@166-315@src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java
      83     24    468      3      94 GenericSegmentTree::GenericSegmentTree@167-260@src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java
      58     16    318      0      68 GenericSegmentTree2::GenericSegmentTree2@195-262@src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree2.java
      30     17    442      0      31 SuffixArrayFast::construct@32-62@src/main/java/com/williamfiset/algorithms/datastructures/suffixarray/SuffixArrayFast.java
      82     27    736      1      97 TreePrinter::getTreeDisplay@23-119@src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java
      22     31    290      3      66 Solution::f@15-80@src/main/java/com/williamfiset/algorithms/dp/examples/domino-and-tromino-tiling/Solution.java
      35     20    593      4      68 LineSegmentLineSegmentIntersection::lineSegmentLineSegmentIntersection@41-108@src/main/java/com/williamfiset/algorithms/geometry/LineSegmentLineSegmentIntersection.java
      58     17    551      1      81 TreeIsomorphismWithBfs::encodeTree@63-143@src/main/java/com/williamfiset/algorithms/graphtheory/treealgorithms/TreeIsomorphismWithBfs.java
      55     23    469      0      69 TspDynamicProgrammingIterative::solve@55-123@src/main/java/com/williamfiset/algorithms/graphtheory/TspDynamicProgrammingIterative.java
      26     17    399      0      26 LongestCommonPrefixArray::SuffixArray::construct@54-79@src/main/java/com/williamfiset/algorithms/strings/LongestCommonPrefixArray.java
      26     17    399      0      26 LongestRepeatedSubstring::SuffixArray::construct@58-83@src/main/java/com/williamfiset/algorithms/strings/LongestRepeatedSubstring.java
      26     17    399      0      26 SubstringVerificationSuffixArray::SuffixArray::construct@56-81@src/main/java/com/williamfiset/algorithms/strings/SubstringVerificationSuffixArray.java

**Comment by Carnoustie** [comment]
Chosen:

- encodeTree() located at lines 63-143 in the file 
src/main/java/com/williamfiset/algorithms/graphtheory/treealgorithms/TreeIsomorphismWithBfs.java      CCN: 17,  LOC:58

- reduce() located at lines 47-105 in the file
 src/main/java/com/williamfiset/algorithms/math/ChineseRemainderTheorem.java
CCN: 13,  LOC:51

**Comment by gustafvh** [comment]
Chosen:

- **LongestCommonPrefixArray** located at lines 54-79 in the file src/main/java/com/williamfiset/algorithms/strings/LongestCommonPrefixArray.java
CCN: 17, LOC: 26

- **LongestRepeatedSubstring** located at lines 58-83 in the file src/main/java/com/williamfiset/algorithms/strings/LongestRepeatedSubstring.java
CCN: 17 , LOC: 26


Replace LongestCommonPrefixArray with bellmanFord located at lines 48-73 in file src/main/java/com/williamfiset/algorithms/graphtheory/BellmanFordAdjacencyList.java

CCN: 9    LOC: 26

Due to testing reasons

**Comment by elibon99** [comment]
Chosen:

- **getTreeDisplay** located at lines 23-120 in the file
src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java
CCN: 27, LOC: 98

- **GenericSegmentTree** located at lines 167-260 in the file
src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java
CCN: 24, LOC: 94



Replace genericSegmentTree() with
bfs() located at lines 194-229 in

./java/com/williamfiset/algorithms/graphtheory/networkflow/examples/EdmondsKarpExample.java

CCN: 9      LOC: 36

Due to testing purposes

**Comment by Klako** [comment]
Chosen:
- **solve** located at lines 55-123 in the file
src/main/java/com/williamfiset/algorithms/graphtheory/TspDynamicProgrammingIterative.java
CCN: 23, LOC 55
- **knn** located at lines 166-315 in the file
src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java
CCN: 91, LOC: 113

**Comment by Gabriel-Acar** [comment]
Chosen:

- **lineSegmentLineSegmentIntersection** located at lines 41-108 in the file src/main/java/com/williamfiset/algorithms/geometry/LineSegmentLineSegmentIntersection.java 
CCN: 20, LOC: 35
- **lcs** located at the lines 15-63 in the file src/main/java/com/williamfiset/algorithms/dp/LongestCommonSubstring.java
CCN: 15, LOC: 26

**Comment by Carnoustie** [comment]
Replace genericSegmentTree() with 
bfs() located at lines 194-229 in

./java/com/williamfiset/algorithms/graphtheory/networkflow/examples/EdmondsKarpExample.java
