### ISSUE TITLE
Research framework for code coverage implementation

### ISSUE THREAD

**Issue by Carnoustie** [GroupFiveSW/Algorithms#9]
Compare Python/ Java for code coverage

**Comment by Klako** [comment]
**Alternative 1:**

Use https://asm.ow2.io/ and edit compiled class files.
[org.objectweb.asm.tree](https://asm.ow2.io/javadoc/org/objectweb/asm/tree/package-summary.html) can be used to easily read contents of classes ,methods, etc.
Overwrite class files with data from [ClassWriter.toByteArray()](https://asm.ow2.io/javadoc/org/objectweb/asm/ClassWriter.html)
Will have to analyze jump instructions in order to find where to put code (might have to check for existing identical code)

**Comment by gustafvh** [comment]
It seems from the assignment that our DIY coverage tool needs to interact with the source code in Java in some way, meaning it does not sound like a great idea to mix languages and introduce Python. **My vote is on using Java because of this**, previous experience and ability to use the classes @Klako mentions above.

**Comment by Klako** [comment]
**Alternative 2:**

Use https://javaparser.org/ to edit source files.
will need to check if code is already inserted.

**Comment by gustafvh** [comment]
The final decision was to chose Java as a language after discussion with the group.
